version: 1.2.0
port: 7054
debug: false
crlsizelimit: 512000
tls:
  enabled: true
  certfile: null
  keyfile: null
  clientauth:
    type: noclientcert
    certfiles: null
ca:
  name: TestOrgACA
  keyfile: null
  certfile: null
  chainfile: null
crl:
  expiry: 24h
registry:
  maxenrollments: -1
  identities:
  - name: admin
    pass: OMX0LmIyXdt8CC9U
    type: client
    affiliation: ''
    attrs:
      hf.Registrar.Roles: '*'
      hf.Registrar.DelegateRoles: '*'
      hf.Revoker: true
      hf.IntermediateCA: true
      hf.GenCRL: true
      hf.Registrar.Attributes: '*'
      hf.AffiliationMgr: true
db:
  type: sqlite3
  datasource: fabric-ca-server.db
  tls:
    enabled: false
    certfiles: null
    client:
      certfile: null
      keyfile: null
ldap:
  enabled: false
  url: ldap://<adminDN>:<adminPassword>@<host>:<port>/<base>
  tls:
    certfiles: null
    client:
      certfile: null
      keyfile: null
  attribute:
    names:
    - uid
    - member
    converters:
    - name: null
      value: null
    maps:
      groups:
      - name: null
        value: null
affiliations: null
signing:
  default:
    usage:
    - digital signature
    expiry: 8760h
  profiles:
    ca:
      usage:
      - cert sign
      - crl sign
      expiry: 43800h
      caconstraint:
        isca: true
        maxpathlen: 0
    tls:
      usage:
      - signing
      - key encipherment
      - server auth
      - client auth
      - key agreement
      expiry: 8760h
csr:
  cn: ca.orga.example.com
  names:
  - C: CN
    ST: Beijing
    L: Chaoyang
    O: TestOrgA
    OU: ''
  hosts:
  - localhost
  - orga.example.com
  ca:
    expiry: 1314000h
    pathlength: 1
bccsp:
  default: SW
  sw:
    hash: SHA2
    security: 256
    filekeystore:
      keystore: msp/keystore
cacount: null
cafiles: null
intermediate:
  parentserver:
    url: null
    caname: null
  enrollment:
    hosts: null
    profile: null
    label: null
  tls:
    certfiles: null
    client:
      certfile: null
      keyfile: null
