version: "3"

services:
  fabric-baas-platform-redis:
    # container_name: fabric-baas-platform-redis
    restart: always
    image: "redis:6.2"
    ports:
      - "6379:6379"
    command: "redis-server --requirepass vc8wNxd1pY9Sj6Qw"
    volumes:
      - ./redis:/data
