version: "3"

services:
  ttp-redis:
    container_name: ttp-redis
    restart: always
    image: "redis:6.2"
    ports:
      - "6379:6379"
    command: "redis-server --requirepass vc8wNxd1pY9Sj6Qw"
    volumes:
      - ./redis:/data
