version: '3.7'

services:
  fabric-baas-platform-ca:
    user: ${UID}:${GID}
    # container_name: fabric-baas-platform-ca
    restart: always
    image: hyperledger/fabric-ca:1.4.10
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=OrdererCA
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:mZFqYztvDju1GUhP -d'
    volumes:
      - ./fabric-ca-server:/etc/hyperledger/fabric-ca-server
