version: '3.7'

services:
  ttp-fabric-ca:
    container_name: ttp-fabric-ca
    restart: always
    image: hyperledger/fabric-ca:1.4.10
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=OrdererCA
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:7055
    ports:
      - 7054:7054
      - 7055:7055
    command: sh -c 'fabric-ca-server start -b admin:mZFqYztvDju1GUhP -d'
    volumes:
      - ./fabric-ca:/etc/hyperledger/fabric-ca-server
