version: '3'

services:
  fabric-baas-minio:
    container_name: fabric-baas-minio
    restart: always
    image: "minio/minio:RELEASE.2020-12-29T23-29-29Z"
    ports:
      - 9000:9000
    command: "minio server /data"
    environment:
      MINIO_ACCESS_KEY: "root"
      MINIO_SECRET_KEY: "bZ9FlZFDqYFk1SL2"
    volumes:
      - ./minio:/data