apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox:1.34.1
      command:
        - sleep
        - "36000"
      imagePullPolicy: Never
  restartPolicy: Always
